### PR TITLE
ci: fall back to the base EVM benchmark harness when the PR harness will not compile

### PR DESCRIPTION
**Pull request by LukaszRozmej**
## Changes

- Probe the base build after copying the PR's opcode benchmark harness into the base worktree
- If that build fails, restore base's own harness sources so the comparison still runs, and flag it in the comparison comment

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [x] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

Reproduced both halves locally against a master worktree: copying #13079's `EvmOpcodesBenchmark.cs` onto master fails the probe build with the same `CS0029` and exit 1, and `git checkout --` followed by a rebuild then succeeds with a clean tree.

#### Requires documentation update

- [ ] Yes
- [x] No

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

## Remarks

`Compare EVM opcode benchmarks (base vs PR)` fails outright on [#13079](https://github.com/NethermindEth/nethermind/pull/13079):

```
nethermind-base-.../Nethermind.Evm.Benchmark/EvmOpcodesBenchmark.cs(222,20): error CS0029:
Cannot implicitly convert type 'delegate*<..., ref int, EvmExceptionType>[]'
                            to 'delegate*<..., ref nint, EvmExceptionType>[]'
The build failed. Fix the build errors and run again.
```

The base side deliberately builds the PR's harness sources so both sides measure with identical code, which requires those sources to compile against the base commit. A PR that changes an EVM API the harness calls — there, the opcode delegate's program counter type — breaks that build, no `COMMENT_BODY` is produced, and the check goes red with no numbers.

This cannot be solved in the harness source: it would have to compile against unmodified master as well, `ref` arguments need an exact type match, `var` cannot type a field, and hiding the pointer type behind an indirection would change what the benchmark measures. Falling back to base's own harness keeps the comparison meaningful whenever the harness itself is unchanged apart from the incompatibility — on #13079 the only differences are the four `int pc` → `nint pc` lines and the field type, so the measurement code is otherwise byte-for-byte identical. When the harness did change materially the comment now says so, rather than the check simply failing.

Cost is one incremental build of `Nethermind.Evm.Benchmark` against base, largely reused by the base benchmark run that follows.

### CODE REVIEW

File: .github/workflows/evm-opcode-benchmark-diff.yml [hunk 1]
```diff
@@ -133,6 +133,17 @@ jobs:
...
 
+          # A PR that changes an EVM API the harness calls (e.g. the opcode delegate signature) leaves
+          # the PR harness uncompilable against base. Fall back to base's own harness so the comparison
+          # still runs; the compare step flags that the two sides measured with different sources.
+          pushd "${BASE_WORKTREE}/src/Nethermind" >/dev/null
+          dotnet restore Benchmarks.slnx --locked-mode
+          if ! dotnet build Nethermind.Evm.Benchmark/Nethermind.Evm.Benchmark.csproj -c Release --no-restore; then
+            git -C "${BASE_WORKTREE}" checkout -- "${benchmark_sources[@]}"
+            echo "BASE_HARNESS_FALLBACK=true" >> "${GITHUB_ENV}"
+          fi
```
[the remark this answers is not in the document]
Comment (LukaszRozmej) [reply .github/workflows/evm-opcode-benchmark-diff.yml:169]: Done in ff2ceb2. The probe now tees into `evm-base-harness-probe.log` (added to the uploaded artifact), and after restoring base's harness it rebuilds — if that rebuild also fails the step fails, so a transient or unrelated breakage can no longer be reported as a harness incompatibility. A `::warning::` annotation is emitted when the fallback fires.

Verified all three paths locally against a master worktree: PR harness copied in -> fallback with exit 0; harness unchanged -> no fallback; an unrelated syntax error planted in base -> step exits 1 with no fallback claimed.

File: .github/workflows/evm-opcode-benchmark-diff.yml [hunk 2]
```diff
@@ -293,6 +304,11 @@ jobs:
           summary_lines.append("## EVM Opcode Benchmark Diff")
           summary_lines.append("")
           summary_lines.append(f"Aggregated runs: base={len(base_logs)}, pr={len(pr_logs)}")
+          if os.environ.get("BASE_HARNESS_FALLBACK") == "true":
+              summary_lines.append(
+                  "⚠️ The PR benchmark harness does not compile against the base commit, so the base "
+                  "side ran its own harness sources. Treat the comparison as indicative if the harness itself changed."
+              )
```
[the remark this answers is not in the document]
Comment (LukaszRozmej) [reply .github/workflows/evm-opcode-benchmark-diff.yml:339]: Agreed — done in ff2ceb2. The probe step exports `BASE_HARNESS_DELTA` from `git diff --shortstat` over the three harness sources, and the comment now renders a `> [!WARNING]` callout (blank-line separated, so it does not lazily absorb the `Noisy rerun opcodes` line) stating the delta. On #13079 it reads `1 file changed, 5 insertions(+), 5 deletions(-)` — confirmed by running the step body locally.

File: .github/workflows/evm-opcode-benchmark-diff.yml [hunk 3]
```diff
@@ -133,6 +133,17 @@ jobs:
             cp "${GITHUB_WORKSPACE}/${source}" "${BASE_WORKTREE}/${source}"
           done
 
+          # A PR that changes an EVM API the harness calls (e.g. the opcode delegate signature) leaves
+          # the PR harness uncompilable against base. Fall back to base's own harness so the comparison
+          # still runs; the compare step flags that the two sides measured with different sources.
+          pushd "${BASE_WORKTREE}/src/Nethermind" >/dev/null
+          dotnet restore Benchmarks.slnx --locked-mode
+          if ! dotnet build Nethermind.Evm.Benchmark/Nethermind.Evm.Benchmark.csproj -c Release --no-restore; then
+            git -C "${BASE_WORKTREE}" checkout -- "${benchmark_sources[@]}"
```
[the remark this answers is not in the document]
Comment (LukaszRozmej) [reply .github/workflows/evm-opcode-benchmark-diff.yml]: Done in ff2ceb2, via `git ls-files` — tracked paths are restored, untracked copies are removed so no stray file is left in the base worktree.

File: .github/workflows/evm-opcode-benchmark-diff.yml [hunk 4]
```diff
@@ -133,6 +133,17 @@ jobs:
             cp "${GITHUB_WORKSPACE}/${source}" "${BASE_WORKTREE}/${source}"
           done
 
+          # A PR that changes an EVM API the harness calls (e.g. the opcode delegate signature) leaves
+          # the PR harness uncompilable against base. Fall back to base's own harness so the comparison
+          # still runs; the compare step flags that the two sides measured with different sources.
+          pushd "${BASE_WORKTREE}/src/Nethermind" >/dev/null
+          dotnet restore Benchmarks.slnx --locked-mode
+          if ! dotnet build Nethermind.Evm.Benchmark/Nethermind.Evm.Benchmark.csproj -c Release --no-restore; then
```
[the remark this answers is not in the document]
Comment (LukaszRozmej) [reply .github/workflows/evm-opcode-benchmark-diff.yml]: Done in ff2ceb2 — the probe builds `Nethermind.Benchmark.Runner.csproj` now, and the step is renamed to `Use PR opcode benchmark harness for base (probe, fall back to base harness)`. Near-zero extra cost since the base benchmark run reuses the output.

**Comment by LukaszRozmej** [comment]
@claude re-review

File: .github/workflows/evm-opcode-benchmark-diff.yml [hunk 5]
```diff
@@ -133,6 +133,34 @@ jobs:
...
+            if [[ "${#tracked[@]}" -gt 0 ]]; then
+              git -C "${BASE_WORKTREE}" checkout -- "${tracked[@]}"
+            fi
+            for source in "${benchmark_sources[@]}"; do
+              git -C "${BASE_WORKTREE}" ls-files --error-unmatch -- "${source}" >/dev/null 2>&1 || rm -f "${BASE_WORKTREE}/${source}"
+            done
+            # A base that fails to build on its own sources was never a harness incompatibility; let it
+            # fail here rather than publish a comparison whose two sides ran different harnesses.
+            dotnet build "${probe_project}" -c Release --no-restore
+            harness_delta="$(git -C "${GITHUB_WORKSPACE}" diff --shortstat "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}" -- "${benchmark_sources[@]}" | sed 's/^[[:space:]]*//')"
```
[the remark this answers is not in the document]
Comment (LukaszRozmej) [reply .github/workflows/evm-opcode-benchmark-diff.yml]: Good catch on the unchanged-harness hole — done in b6f0d9d.

`harness_delta` is now computed before the probe, with `|| true` so a git failure can't abort a run the probe may still pass, and the fallback is gated on it being non-empty: an empty delta (harness identical to base, or the diff couldn't be taken) exits 1 with an `::error::` rather than claiming an incompatibility. `not reported` is gone from both the env var and the warning — the delta is guaranteed non-empty wherever it's printed.

Exercised the step body locally against stubbed `git`/`dotnet` over five paths: probe passes (no fallback, exit 0); harness changed + PR harness fails + base builds (fallback, exit 0, warning carries the delta); harness unchanged + probe fails (exit 1, `::error::`, no `BASE_HARNESS_FALLBACK`); base broken on its own sources (exit 1); `git diff` failing (exit 1, no false claim).

File: .github/workflows/evm-opcode-benchmark-diff.yml [hunk 6]
```diff
@@ -133,6 +133,34 @@ jobs:
...
+            mapfile -t tracked < <(git -C "${BASE_WORKTREE}" ls-files -- "${benchmark_sources[@]}")
+            if [[ "${#tracked[@]}" -gt 0 ]]; then
+              git -C "${BASE_WORKTREE}" checkout -- "${tracked[@]}"
+            fi
+            for source in "${benchmark_sources[@]}"; do
+              git -C "${BASE_WORKTREE}" ls-files --error-unmatch -- "${source}" >/dev/null 2>&1 || rm -f "${BASE_WORKTREE}/${source}"
+            done
+            # A base that fails to build on its own sources was never a harness incompatibility; let it
+            # fail here rather than publish a comparison whose two sides ran different harnesses.
+            dotnet build "${probe_project}" -c Release --no-restore
```
[the remark this answers is not in the document]
Comment (LukaszRozmej) [reply .github/workflows/evm-opcode-benchmark-diff.yml]: Agreed — done in b6f0d9d, the restored-harness build now `tee -a`s into the same `evm-base-harness-probe.log`. In the stubbed "base is broken on its own sources" run the log reads:

```
build#1: compiling
build#1 error CS0029
build#2: compiling
build#2 error CS1002 base is broken
```

so the artifact ends with the evidence that base itself is broken rather than the PR-harness errors. `pipefail` still propagates the failure and the step exits 1.

**Review by svlachakis — APPROVED** [review]

**Review by benaadams — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
@claude re-review
